<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726141112 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE cf_user_role (user_id INT NOT NULL, role_id INT NOT NULL, INDEX IDX_1F862B24A76ED395 (user_id), INDEX IDX_1F862B24D60322AC (role_id), PRIMARY KEY(user_id, role_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE cf_user_role ADD FOREIGN KEY (user_id) REFERENCES cf_user(id)");
        $this->addSql("ALTER TABLE cf_user_role ADD FOREIGN KEY (role_id) REFERENCES cf_role(id)");
        $this->addSql("DROP TABLE user_role");
        $this->addSql("ALTER TABLE cf_user ADD last_name VARCHAR(255) NOT NULL, ADD first_name VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, INDEX IDX_2DE8C6A3A76ED395 (user_id), INDEX IDX_2DE8C6A3D60322AC (role_id), PRIMARY KEY(user_id, role_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE user_role ADD CONSTRAINT user_role_ibfk_1 FOREIGN KEY (user_id) REFERENCES cf_user(id)");
        $this->addSql("ALTER TABLE user_role ADD CONSTRAINT user_role_ibfk_2 FOREIGN KEY (role_id) REFERENCES cf_role(id)");
        $this->addSql("DROP TABLE cf_user_role");
        $this->addSql("ALTER TABLE cf_user DROP last_name, DROP first_name");
    }
}
