<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110805153743 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE cf_user_groups (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_3F46806AA76ED395 (user_id), INDEX IDX_3F46806AFE54D947 (group_id), PRIMARY KEY(user_id, group_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE UserGroup (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE cf_user_groups ADD FOREIGN KEY (user_id) REFERENCES cf_user(id)");
        $this->addSql("ALTER TABLE cf_user_groups ADD FOREIGN KEY (group_id) REFERENCES UserGroup(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE cf_user_groups DROP FOREIGN KEY ");
        $this->addSql("DROP TABLE cf_user_groups");
        $this->addSql("DROP TABLE UserGroup");
    }
}
