<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110725155713 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE cf_settings (id INT AUTO_INCREMENT NOT NULL, defaultLanguage VARCHAR(10) NOT NULL, defaultTheme VARCHAR(100) NOT NULL, userFormat VARCHAR(30) NOT NULL, useGravatar TINYINT(1) NOT NULL, smtpHost VARCHAR(255) NOT NULL, smtpPort VARCHAR(5) NOT NULL, smtpUser VARCHAR(255) NOT NULL, smtpPassword VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE cf_settings");
    }
}
