<?php

namespace CuteFlow\CoreBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getFindAllQuery()->getResult();
    }

    public function findOneByUsername($username)
    {
        return $this->createQueryBuilder('u')
                              ->where('u.username=:username')
                                ->setParameter('username', $username)
                              ->andWhere('u.deletedAt IS NULL')
                              ->getQuery()
                              ->getSingleResult();
    }

    public function getFindAllQuery()
    {
        return $this->createQueryBuilder('u')
                              ->where('u.deletedAt IS NULL')
                              ->getQuery();
    }
}